import Head from 'next/head'

import { AboutSectionLayout, LinkButton, PageLayout } from '@/components'

const About = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <main>
        <PageLayout>
          <AboutSectionLayout title={'Can’t wait to start?'}>
            <LinkButton
              buttonContent={'Get started'}
              link={'/'}
            />
          </AboutSectionLayout>
        </PageLayout>
      </main>
    </>
  )
}

export default About
